// <auto-generated />
namespace Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class makeregularexperssiononcontactmedicine : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(makeregularexperssiononcontactmedicine));
        
        string IMigrationMetadata.Id
        {
            get { return "202205152311396_make regular experssion on contact medicine"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
